### ISSUE TITLE
Publisher: Can't edit the title of artefacts in new editions

### ISSUE THREAD

**Issue by langphil** [theodi/publisher#136] opened 2015-06-02 15:40 UTC
Hi,

Just an issue we're having with publisher where titles in new editions of artefacts cannot be edited. They revert back to there original text upon saving. 

@floppy @pezholio

**Comment by Floppy** [comment] 2015-06-02 15:42
This is a known issue, right? It's been hanging around a while, I admit. I think it's a dupe of #135.

**Comment by langphil** [comment] 2015-06-02 15:43
Ah yes. I’d thought it had been fixed and created an new issue. I’ll delete now.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 2 June 2015 at 16:42:12, James Smith (notifications@github.com) wrote:

This is a known issue, right? It's been hanging around a while, I admit. I think it's a dupe of #135.

**Comment by Floppy** [comment] 2015-06-02 15:46
Sorry, no, it's been a victim of I don't know what. Soon :(

**Closed by Floppy** 2015-06-02 15:46 UTC
